/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const VehicleCategory = IDL.Variant({
  'new' : IDL.Null,
  'used' : IDL.Null,
});
export const Vehicle = IDL.Record({
  'model' : IDL.Text,
  'name' : IDL.Text,
  'year' : IDL.Nat,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'category' : VehicleCategory,
  'price' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ServiceStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Time = IDL.Int;
export const ServiceBooking = IDL.Record({
  'id' : IDL.Nat,
  'vehicleNumberPlate' : IDL.Text,
  'customerName' : IDL.Text,
  'status' : ServiceStatus,
  'serviceType' : IDL.Text,
  'creationTimestamp' : Time,
  'preferredDate' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addVehicle' : IDL.Func([Vehicle], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBooking' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'getAllBookings' : IDL.Func([], [IDL.Vec(ServiceBooking)], ['query']),
  'getBookingsByNumberPlate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ServiceBooking)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAvailableVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
  'removeVehicle' : IDL.Func([IDL.Nat], [], []),
  'updateBookingStatus' : IDL.Func([IDL.Nat, ServiceStatus], [], []),
  'updateVehicle' : IDL.Func([IDL.Nat, Vehicle], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const VehicleCategory = IDL.Variant({ 'new' : IDL.Null, 'used' : IDL.Null });
  const Vehicle = IDL.Record({
    'model' : IDL.Text,
    'name' : IDL.Text,
    'year' : IDL.Nat,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'category' : VehicleCategory,
    'price' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ServiceStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Time = IDL.Int;
  const ServiceBooking = IDL.Record({
    'id' : IDL.Nat,
    'vehicleNumberPlate' : IDL.Text,
    'customerName' : IDL.Text,
    'status' : ServiceStatus,
    'serviceType' : IDL.Text,
    'creationTimestamp' : Time,
    'preferredDate' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addVehicle' : IDL.Func([Vehicle], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBooking' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'getAllBookings' : IDL.Func([], [IDL.Vec(ServiceBooking)], ['query']),
    'getBookingsByNumberPlate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ServiceBooking)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAvailableVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
    'removeVehicle' : IDL.Func([IDL.Nat], [], []),
    'updateBookingStatus' : IDL.Func([IDL.Nat, ServiceStatus], [], []),
    'updateVehicle' : IDL.Func([IDL.Nat, Vehicle], [], []),
  });
};

export const init = ({ IDL }) => { return []; };