/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ServiceBooking {
  'id' : bigint,
  'vehicleNumberPlate' : string,
  'customerName' : string,
  'status' : ServiceStatus,
  'serviceType' : string,
  'creationTimestamp' : Time,
  'preferredDate' : string,
  'phone' : string,
}
export type ServiceStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Vehicle {
  'model' : string,
  'name' : string,
  'year' : bigint,
  'description' : string,
  'available' : boolean,
  'category' : VehicleCategory,
  'price' : bigint,
}
export type VehicleCategory = { 'new' : null } |
  { 'used' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addVehicle' : ActorMethod<[Vehicle], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBooking' : ActorMethod<
    [string, string, string, string, string],
    bigint
  >,
  'getAllBookings' : ActorMethod<[], Array<ServiceBooking>>,
  'getBookingsByNumberPlate' : ActorMethod<[string], Array<ServiceBooking>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAvailableVehicles' : ActorMethod<[], Array<Vehicle>>,
  'removeVehicle' : ActorMethod<[bigint], undefined>,
  'updateBookingStatus' : ActorMethod<[bigint, ServiceStatus], undefined>,
  'updateVehicle' : ActorMethod<[bigint, Vehicle], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];