/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ServiceBooking {
    id: bigint;
    vehicleNumberPlate: string;
    customerName: string;
    status: ServiceStatus;
    serviceType: string;
    creationTimestamp: Time;
    preferredDate: string;
    phone: string;
}
export type Time = bigint;
export interface Vehicle {
    model: string;
    name: string;
    year: bigint;
    description: string;
    available: boolean;
    category: VehicleCategory;
    price: bigint;
}
export enum ServiceStatus {
    pending = "pending",
    completed = "completed",
    inProgress = "inProgress"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum VehicleCategory {
    new_ = "new",
    used = "used"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addVehicle(vehicle: Vehicle): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createBooking(vehicleNumberPlate: string, customerName: string, phone: string, serviceType: string, preferredDate: string): Promise<bigint>;
    getAllBookings(): Promise<Array<ServiceBooking>>;
    getBookingsByNumberPlate(vehicleNumberPlate: string): Promise<Array<ServiceBooking>>;
    getCallerUserRole(): Promise<UserRole>;
    isCallerAdmin(): Promise<boolean>;
    listAvailableVehicles(): Promise<Array<Vehicle>>;
    removeVehicle(id: bigint): Promise<void>;
    updateBookingStatus(id: bigint, newStatus: ServiceStatus): Promise<void>;
    updateVehicle(id: bigint, vehicle: Vehicle): Promise<void>;
}
import type { ServiceBooking as _ServiceBooking, ServiceStatus as _ServiceStatus, Time as _Time, UserRole as _UserRole, Vehicle as _Vehicle, VehicleCategory as _VehicleCategory } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addVehicle(arg0: Vehicle): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addVehicle(to_candid_Vehicle_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addVehicle(to_candid_Vehicle_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createBooking(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async getAllBookings(): Promise<Array<ServiceBooking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBookings();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBookings();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingsByNumberPlate(arg0: string): Promise<Array<ServiceBooking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByNumberPlate(arg0);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByNumberPlate(arg0);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAvailableVehicles(): Promise<Array<Vehicle>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAvailableVehicles();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAvailableVehicles();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeVehicle(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeVehicle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeVehicle(arg0);
            return result;
        }
    }
    async updateBookingStatus(arg0: bigint, arg1: ServiceStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBookingStatus(arg0, to_candid_ServiceStatus_n19(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBookingStatus(arg0, to_candid_ServiceStatus_n19(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateVehicle(arg0: bigint, arg1: Vehicle): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVehicle(arg0, to_candid_Vehicle_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVehicle(arg0, to_candid_Vehicle_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_ServiceBooking_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceBooking): ServiceBooking {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceStatus): ServiceStatus {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_VehicleCategory_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VehicleCategory): VehicleCategory {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Vehicle_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Vehicle): Vehicle {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    model: string;
    name: string;
    year: bigint;
    description: string;
    available: boolean;
    category: _VehicleCategory;
    price: bigint;
}): {
    model: string;
    name: string;
    year: bigint;
    description: string;
    available: boolean;
    category: VehicleCategory;
    price: bigint;
} {
    return {
        model: value.model,
        name: value.name,
        year: value.year,
        description: value.description,
        available: value.available,
        category: from_candid_VehicleCategory_n17(_uploadFile, _downloadFile, value.category),
        price: value.price
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    vehicleNumberPlate: string;
    customerName: string;
    status: _ServiceStatus;
    serviceType: string;
    creationTimestamp: _Time;
    preferredDate: string;
    phone: string;
}): {
    id: bigint;
    vehicleNumberPlate: string;
    customerName: string;
    status: ServiceStatus;
    serviceType: string;
    creationTimestamp: Time;
    preferredDate: string;
    phone: string;
} {
    return {
        id: value.id,
        vehicleNumberPlate: value.vehicleNumberPlate,
        customerName: value.customerName,
        status: from_candid_ServiceStatus_n10(_uploadFile, _downloadFile, value.status),
        serviceType: value.serviceType,
        creationTimestamp: value.creationTimestamp,
        preferredDate: value.preferredDate,
        phone: value.phone
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
}): ServiceStatus {
    return "pending" in value ? ServiceStatus.pending : "completed" in value ? ServiceStatus.completed : "inProgress" in value ? ServiceStatus.inProgress : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    new: null;
} | {
    used: null;
}): VehicleCategory {
    return "new" in value ? VehicleCategory.new : "used" in value ? VehicleCategory.used : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Vehicle>): Array<Vehicle> {
    return value.map((x)=>from_candid_Vehicle_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ServiceBooking>): Array<ServiceBooking> {
    return value.map((x)=>from_candid_ServiceBooking_n8(_uploadFile, _downloadFile, x));
}
function to_candid_ServiceStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceStatus): _ServiceStatus {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_VehicleCategory_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VehicleCategory): _VehicleCategory {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Vehicle_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Vehicle): _Vehicle {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    model: string;
    name: string;
    year: bigint;
    description: string;
    available: boolean;
    category: VehicleCategory;
    price: bigint;
}): {
    model: string;
    name: string;
    year: bigint;
    description: string;
    available: boolean;
    category: _VehicleCategory;
    price: bigint;
} {
    return {
        model: value.model,
        name: value.name,
        year: value.year,
        description: value.description,
        available: value.available,
        category: to_candid_VehicleCategory_n3(_uploadFile, _downloadFile, value.category),
        price: value.price
    };
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceStatus): {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
} {
    return value == ServiceStatus.pending ? {
        pending: null
    } : value == ServiceStatus.completed ? {
        completed: null
    } : value == ServiceStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VehicleCategory): {
    new: null;
} | {
    used: null;
} {
    return value == VehicleCategory.new ? {
        new_: null
    } : value == VehicleCategory.used ? {
        used: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
